title: Walrus
description: Make the most of your card cloning devices.
url: http://project-walrus.io

github_username: megabug/Walrus

google_analytics: UA-115651889-1

markdown: kramdown
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

header_pages:
  - docs/getting-started.md
  - development.md
  - lumpy.md

exclude:
  - Gemfile
  - Gemfile.lock
