# Site settings
title: Walrus
description: Make the most of your card cloning devices.
url: http://project-walrus.io
github_username: megabug/ProjectWalrus

# Build settings
markdown: kramdown
theme: minima
